ccflags-y += -Idrivers/media/platform/msm/camera_v2_eur
ccflags-y += -Idrivers/media/platform/msm/camera_v2_eur/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_eur/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
obj-$(CONFIG_MSM_OTP) += msm_otp.o