ccflags-y += -Idrivers/media/platform/msm/camera_v2_eur
ccflags-y += -Idrivers/media/platform/msm/camera_v2_eur/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_eur/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
