ccflags-y += -Idrivers/media/platform/msm/camera_v2_eur
ccflags-y += -Idrivers/media/platform/msm/camera_v2_eur/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_eur/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
